DISPLAY_CATEGORIES_ON_MENU = False
DISPLAY_CATEGORIES_ON_POSTINFO = True
DISPLAY_CATEGORIES_ON_SUBMENU = False
TAG_CLOUD_MAX_ITEMS = 20

DISPLAY_SEARCH_FORM = True

PAGES_SORT_ATTRIBUTE = 'order'

THEME = 'theme'
