name: Daily Publisher

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      MAIL_API_KEY: ${{ secrets.MAILGUN_API_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - run: |
        python -m pip install -r requirements.txt
        flake8 scripts/
        mypy --strict --ignore-missing-imports --install-types --non-interactive scripts/

    - run: python -m fire scripts/notifier.py main
